local DialogueData = {
	["Intro"] = {
		"You climbed your way out of the Tomb and appeared in some kind of abandoned Chapel..",
		"Since you´ve found another bonfire you know this is the path that leads to your destiny..",
		"Your only option is to keep moving forward."
	},

	["EndDialogue"] = {
		"You sucessfully challenged the Knight of The Sun and beat him with your wisdom of combat..",
		"You are now free to flee from this place."
	},

	-- Zde si můžeš přidat další: ["ID"] = {"Text 1", "Text 2"},
}

return DialogueData
