local DialogueData = {
	["Intro"] = {
		"You have made it to your final destination..",
		"The only thing that stands in your way is him..",
		"Slay the Great Tyrant and set all the souls free that were taken by him..",
		"You cannot fall here."
	},

	["EndDialogue"] = {
		"You sucessfully challenged the Knight of The Sun and beat him with your wisdom of combat..",
		"You are now free to flee from this place."
	},

	-- Zde si můžeš přidat další: ["ID"] = {"Text 1", "Text 2"},
}

return DialogueData
