local DialogueData = {
	["Intro"] = {
		"You wake up inside your rotting cell but something seems off..",
		"You quickly notice that the guards and all the prisoners were massacred by something unknown..",
		"All thats left for you is to escape this damned Dungeon."
	},

	["ArcaneKnowledge"] = {
		"Je tu tma a zima...",
		"Slyšel jsem něco v křoví!",
		"Raději bychom měli jít dál."
	},

	-- Zde si můžeš přidat další: ["ID"] = {"Text 1", "Text 2"},
}

return DialogueData
